<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Tests.UI.Targets/Lombiq.MSBuild.Tests.UI.Targets.props" />

  <PropertyGroup>
    <Title>Lombiq Hosting - Tenants FeaturesGuard - UI Test Extensions</Title>
    <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
    <Description>Extension methods that test various features in Lombiq Hosting - Tenants FeaturesGuard, with the help of Lombiq UI Testing Toolbox for Orchard Core. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Tenants;LombiqHostingSuite;Shouldly;xUnit;UITesting;Testing</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Tenants</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.FeaturesGuard.Tests.UI/Readme.md</PackageProjectUrl>
  </PropertyGroup>

</Project>
