<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <ImportLombiqHelpfulLibrariesOrchardCore>true</ImportLombiqHelpfulLibrariesOrchardCore>
    <ImportLombiqHelpfulExtensions>true</ImportLombiqHelpfulExtensions>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true' "/>

  <PropertyGroup>
    <Title>Lombiq Hosting - Tenants Email Quota Management for Orchard Core</Title>
    <Copyright>Copyright © 2023, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Tenants Email Quota Management for Orchard Core: With the help of this module, you can set restrictions regarding maximum email sent per tenant. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Multitenancy;SaaS</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Tenants</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.EmailQuotaManagement/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Admin" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Email" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Email.Azure" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Email.Smtp" Version="2.1.0" />
    <PackageReference Include="OrchardCore.AdminDashboard" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Email.Abstractions" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Infrastructure.Abstractions" Version="2.1.0" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true' "/>

</Project>
