<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Hosting - Tenants Email Quota Management for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2023, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Tenants Email Quota Management for Orchard Core: With the help of this module, you can set restrictions regarding maximum email sent per tenant. See the project website for detailed documentation.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Multitenancy;SaaS</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Tenants</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.EmailQuotaManagement/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Admin" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Email" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Email.Azure" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Email.Smtp" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.AdminDashboard" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.ResourceManagement" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Email.Abstractions" Version="3.0.0-preview-18937" />
    <PackageReference Include="OrchardCore.Infrastructure.Abstractions" Version="3.0.0-preview-18937" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
    <ProjectReference Include="..\..\Lombiq.HelpfulExtensions\Lombiq.HelpfulExtensions\Lombiq.HelpfulExtensions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.6.1-alpha.5.osoe-925" />
    <PackageReference Include="Lombiq.HelpfulExtensions" Version="11.1.1-alpha.5.osoe-925" />
  </ItemGroup>
</Project>
