<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Hosting - Tenants Idle Tenant Management for Orchard Core</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Tenants Idle Tenant Management for Orchard Core: With the help of this module, you can ensure that any tenant where the feature is enabled will shutdown after a preset time is elapsed. This can be used to free up resources..</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Multitenancy;SaaS</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Tenants</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.IdleTenantManagement/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Abstractions" Version="3.0.0-preview-18907" />
    <PackageReference Include="OrchardCore" Version="3.0.0-preview-18907" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18907" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Readme.md" />
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
