<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="2.0.1" />

  <PropertyGroup>
    <Title>Lombiq Hosting - Tenants Health Checks for Orchard Core</Title>
    <CopyrightYear>2021</CopyrightYear>
    <DescriptionBody>Multi-tenancy related health check improvements.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Multitenancy;SaaS;HealthChecks</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Tenants</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.HealthChecks/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Tenants" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.HealthChecks" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="2.0.1" />
</Project>
