<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Hosting - Tenants Idle Tenant Management for Orchard Core - UI Test Extensions</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Tenants Idle Tenant Management for Orchard Core - UI Test Extensions: Extension methods that test tenants idle management for Orchard Core. </Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Multitenancy;SaaS</PackageTags>
     <RepositoryUrl>https://github.com/Lombiq/Hosting-Tenants</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Tenants/blob/dev/Lombiq.Hosting.Tenants.IdleTenantManagement.Tests.UI/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\..\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Lombiq.Tests.UI.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.Tests.UI" Version="10.0.2-preview.0.occ-245" />
  </ItemGroup>

  <ItemGroup>
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
    <None Include="Readme.md" />
  </ItemGroup>

</Project>
